name: Take screenshots

on:
  push:
    branches:
      - main

  schedule:
    - cron: "7 7 * * 1" # Every Monday at 7:07am UTC

jobs:
  take-screenshots:
    runs-on: macos-latest

    strategy:
      matrix:
        include:
          # - url: perperpet.com
          #   filename_prefix: perperpet.com
          - url: project-showcase.jweboy.asia
            filename_prefix: project-showcase

      max-parallel: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        with:
          ref: main
          lfs: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Playwright and browser
        run: |
          npm install playwright
          npx playwright install chromium

      - name: Take screenshots
        run: |
          today=$(date +"%Y-%m-%d")
          screenshot_path="screenshots/${{ matrix.filename_prefix }}.$today.png"

          echo "today=$today" >> "$GITHUB_ENV"
          echo "screenshot_path=$screenshot_path" >> "$GITHUB_ENV"

          mkdir -p "$(dirname "$screenshot_path")"

          if [[ -f "$screenshot_path" ]]; then exit 0; fi

          npx playwright screenshot \
              --full-page \
              --wait-for-timeout 10000 \
              "${{ matrix.url }}" "$screenshot_path"

      - name: Push changes to Github
        run: |
          git add "$screenshot_path"
          git commit -m "Add screenshot for ${{ matrix.url }} for $today" || exit 0
          git push origin main
